#!/bin/bash
# Created by: WestleyR
# Email: westleyr@nym.hush.com
# Url: https://github.com/WestleyR/gpack
# Last modified date: 2020-04-21
#
# This file is licensed under the terms of
#
# The Clear BSD License
#
# Copyright (c) 2019-2020 WestleyR
# All rights reserved.
#
# This software is licensed under a Clear BSD License.
#

set -e

for f in $(ls -1 ${HOME}/.gpack/packages/); do
  if test -d "${HOME}/.gpack/packages/${f}"; then
    for p in $(ls -1 ${HOME}/.gpack/packages/${f}); do
      if [ -z "$1" ]; then
        echo "${f}/${p}"
      else
        echo "${f}/${p}" | grep --color=always "$1" || true
      fi
    done
  fi
done

# vim: tabstop=2 shiftwidth=2 expandtab autoindent softtabstop=0
