#!/bin/bash

set -e

if [ -z $1 ]; then
  echo "No script to install"
  exit 1
fi

# get the pkg
source $1

wget -q --show-progress -O ${gpack_prefix}/package.tar.gz ${TARBALL}
tar -xf ${gpack_prefix}/package.tar.gz -C ${gpack_prefix}

cd ${gpack_prefix}/${UNTAR_DIR}

if [ ! -z "${INSTALL_LIB}" ]; then
  ${INSTALL_LIB} &> /dev/null

  mkdir -p ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/lib
  mkdir -p ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include

  for l in ${LIBRARIES}; do
    cp -f $l ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/lib
  done
  for h in ${HEADER_FILES}; do
    cp -f $h ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include
  done

  for l in $(ls -1 ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/lib); do
    echo "Installing files: $l"
    ln -f -s "${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/lib/$l" ${HOME}/.lib
  done

  for h in $(ls -1 ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include); do
    echo "Installing files: $h"
    ln -f -s "${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include/$h" ${HOME}/.lib/include
  done
fi

if [ ! -z "${INSTALL_CMD}" ]; then

  ${INSTALL_CMD} &> /dev/null

  cd ${gpack_prefix}/bin

  mkdir -p ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/bin

  echo "Copying files..."
  for b in $(ls -1); do
    cp -f "${gpack_prefix}/bin/$b" ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/bin
  done

  echo "Installing files..."
  for c in $(ls -1 ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/bin); do
    ln -f -s "${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/bin/$c" ${HOME}/.gpack/bin
  done
fi

echo $PKG_VERSION > ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/version.gpack

# vim: tabstop=2 shiftwidth=2 expandtab autoindent softtabstop=0
