#!/bin/bash

set -e

if [ -z $1 ]; then
  echo "No script to install"
  exit 1
fi

# get the pkg
source $1

if ! wget -q --show-progress -O ${gpack_prefix}/package.tar.gz ${TARBALL} ; then
  echo "ERROR: failed to download tarball from: ${TARBALL}"
  exit 1
fi
tar -xf ${gpack_prefix}/package.tar.gz -C ${gpack_prefix}

cd ${gpack_prefix}/${UNTAR_DIR}

build_log=${gpack_prefix}/build.log

if [ ! -z "${DEP_PKGS}" ]; then
  echo "I: Installing deps: ${DEP_PKGS}..."
  for d in ${DEP_PKGS}; do
    echo "I: Installing: ${d}..."
    if ! gpack install $d ; then
      echo "ERROR: Failed to install deps: ${d}"
      exit 1
    fi
  done
fi

if [ ! -z "${INSTALL_LIB}" ]; then
  if ! ${INSTALL_LIB} &> ${build_log} ; then
    echo
    echo "ERROR: failed to compile libraries"
    echo "last 10 lines from: ${build_log}"
    echo
    tail ${build_log}
    echo
    exit 1
  fi

  mkdir -p ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/lib
  mkdir -p ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include

  echo "Copying files..."
  for l in ${LIBRARIES}; do
    cp -f $l ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/lib
  done
  for h in ${HEADER_FILES}; do
    cp -f $h ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include
  done

  echo "Installing files..."
  mkdir -p ${HOME}/.local/lib
  for l in $(ls -1 ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/lib); do
    ln -f -s "${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/lib/$l" ${HOME}/.local/lib
  done

  mkdir -p ${HOME}/.local/include
  for h in $(ls -1 ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include); do
    ln -f -s "${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include/$h" ${HOME}/.local/include
  done
fi

if [ ! -z "${INSTALL_CMD}" ]; then
  if ! ${INSTALL_CMD} &> ${build_log} ; then
    echo
    echo "ERROR: failed to compile binary"
    echo "last 10 lines from: ${build_log}"
    echo
    tail ${build_log}
    echo
    exit 1
  fi

  cd ${gpack_prefix}/bin

  mkdir -p ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/bin

  echo "Copying files..."
  for b in $(ls -1); do
    cp -f "${gpack_prefix}/bin/$b" ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/bin
  done

  echo "Installing files..."
  for c in $(ls -1 ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/bin); do
    ln -f -s "${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/bin/$c" ${HOME}/.gpack/bin
  done
fi

echo $PKG_VERSION > ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/version.gpack

# vim: tabstop=2 shiftwidth=2 expandtab autoindent softtabstop=0
