#!/bin/bash
# Created by: WestleyR
# email: westleyr@nym.hush.com
# Date: Jan 9, 2020
# https://github.com/WestleyR/gpack
# version-1.0.0
#
# The Clear BSD License
#
# Copyright (c) 2019 WestleyR
# All rights reserved.
#
# This software is licensed under a Clear BSD License.
#

set -e

for f in $(ls -1 ${HOME}/.gpack/packages/); do
  if test -d "${HOME}/.gpack/packages/${f}"; then
    for p in $(ls -1 ${HOME}/.gpack/packages/${f}); do
      if [ -z "$1" ]; then
        echo "${f}/${p}"
      else
        echo "${f}/${p}" | grep --color=always "$1" || true
      fi
    done
  fi
done

# vim: tabstop=2 shiftwidth=2 expandtab autoindent softtabstop=0
