#!/bin/sh
# Created by: WestleyR
# email: westleyr@nym.hush.com
# Date: Jun 22, 2019
# https://github.com/WestleyR/gpack
# version-1.0.0
#
# The Clear BSD License
#
# Copyright (c) 2019 WestleyR
# All rights reserved.
#
# This software is licensed under a Clear BSD License.
#

PKG_LIST="pkg.list"

TMP_FILE="/tmp/gpack-pkg-list.tmp"

if [ -x $1 ]; then
    echo "E: Not enought arguments"
    exit 1
fi

remove_pkg() {
    pkg_name=`echo "$1" | rev | cut -d / -f 1 | rev`
    url_name=`echo "$1" | rev | cut -d / -f 2 | rev`
    url_name=`echo "${url_name}_${pkg_name}"`

    PKG_ZIP="/tmp/usr/local/gpack-repo/zip/${url_name}.zip"
    PKG_NAME="/tmp/usr/local/gpack-repo/repo/${pkg_name}-master"

    if [ -x $(cat "$PKG_LIST" | grep "$1") ]; then
        echo "E: $1 is not installed"
        exit 1
    fi

    echo
    echo "!!!WARNING!!!"
    echo
    echo "Removing: $PKG_ZIP ..."
    sleep 3s
    rm -r "$PKG_ZIP"
    echo "Removing: $PKG_NAME ..."
    sleep 3s
    rm -r "$PKG_NAME"

    cat "$PKG_LIST" | grep -v "$1" > /tmp/gpack-tmp-list.tmp
    mv /tmp/gpack-tmp-list.tmp "$PKG_LIST"
}

for p in $@; do
    remove_pkg "$p"
done

#
# End gpack-remove-pkg
#
