#!/bin/bash

set -e

cd ${HOME}/.gpack/gpack

if ! git diff --name-status --exit-code; then
    echo "gpack has un-commited changes; aborting"
    #exit 1
fi

git pull origin master

make
make install

# vim: tabstop=2 shiftwidth=2 expandtab autoindent softtabstop=0
