#!/bin/sh
# Created by: WestleyR
# email: westleyr@nym.hush.com
# Date: Jun 22, 2019
# https://github.com/WestleyR/gpack
# version-1.0.0
#
# The Clear BSD License
#
# Copyright (c) 2019 WestleyR
# All rights reserved.
#
# This software is licensed under a Clear BSD License.
#

PKG_FILE="pkg.list"

if [ -x $1 ]; then
    echo "E: Not enought arguments"
    exit 1
fi

echo "$1" >> "$PKG_FILE"

#
# End gpack-add-pkg
#
