#!/bin/bash
# Created by: WestleyR
# Email: westleyr@nym.hush.com
# Url: https://github.com/WestleyR/gpack
# Last modified date: 2020-05-17
#
# This file is licensed under the terms of
#
# The Clear BSD License
#
# Copyright (c) 2019-2020 WestleyR
# All rights reserved.
#
# This software is licensed under a Clear BSD License.
#

set -e

nothing_to_upgrade=0

for f in $(ls -1 ${HOME}/.gpack/installed/); do
  for p in $(ls -1 ${HOME}/.gpack/installed/${f}/); do

    if test -f ${HOME}/.gpack/packages/${f}/${p} ; then
      source ${HOME}/.gpack/packages/${f}/${p}
      current_version=`cat ${HOME}/.gpack/installed/${f}/${p}/version.gpack`

      if [[ "$current_version" != "$PKG_VERSION" ]]; then
        echo "I: Package out-of-date: ${f}/${p}"
        gpack install --overide "${f}/${p}"
        nothing_to_upgrade=1
      fi
    else
      echo "WARNING: untracked package installed: ${HOME}/.gpack/packages/${f}/${p}"
    fi
  done
done

if [ $nothing_to_upgrade -eq 0 ]; then
  echo "I: Already up-to-date"
fi

# vim: tabstop=2 shiftwidth=2 expandtab autoindent softtabstop=0
