#!/bin/bash
# Created by: WestleyR
# Email: westleyr@nym.hush.com
# Url: https://github.com/WestleyR/gpack
# Last modified date: 2020-04-21
#
# This file is licensed under the terms of
#
# The Clear BSD License
#
# Copyright (c) 2019-2020 WestleyR
# All rights reserved.
#
# This software is licensed under a Clear BSD License.
#

export gpack_prefix=$(mktemp -d --suffix=-${1} 2> /dev/null || mktemp -d)

# vim: tabstop=2 shiftwidth=2 expandtab autoindent softtabstop=0
